# Generated by Django 5.2.8 on 2025-11-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('place', models.CharField(max_length=10)),
            ],
        ),
    ]
